### ISSUE TITLE
sdk does not work with lxc 2.0.7

### ISSUE THREAD

**Issue by l0rb** [insys-icom/M3_Container#19]
The sdk container can not be started with lxc version 2.0.7

**Comment by m-kress** [comment]
True. 
To solve this, please modify the config file for LXC to the previous syntax:

lxc.network.type = none
lxc.rootfs = /var/lib/lxc/m3sdk/rootfs
lxc.haltsignal = SIGUSR1
lxc.utsname = m3sdk
lxc.tty = 10
lxc.pts = 1024
lxc.cap.drop = audit_control audit_write dac_read_search fsetid ipc_owner linux_immutable mac_admin mac_override mknod setfcap sys_admin sys_boot sys_module sys_pacct sys_ptrace sys_rawio sys_resource sys_time sys_tty_config syslog
lxc.mount.entry = proc proc proc nodev,noexec,nosuid 0 0
lxc.mount.entry = sysfs sys sysfs ro 0 0

**Comment by m-kress** [comment]
Does the comment above solve this issue and can be closed? Or do you wish for another solution?

**Comment by l0rb** [comment]
This is a sufficient work-around.
