### ISSUE TITLE
dns lookup in sdk lxc container doesn't work out of the box

### ISSUE THREAD

**Issue by NANASHI0X74** [insys-icom/M3_Container#21]
Problem: in /etc/resolv.conf there's a nameserver configured that's in a private network (192.168.200.2 in 192.168.0.0/16) so this isn't necessarily reachable from any network

Suggestion: use a public nameserver like 1.1.1.1 or 8.8.8.8 or mention that dns has to be configured

Steps to reproduce: I'm trying to build a container for an SCR Series Device (I'm not an employee of insys, so am not in the same network :) ). I followed the tutorial on how to run the sdk lxc container and proceded to https://github.com/insys-icom/M3_Container/blob/master/doc/1st_steps.md , but step 2 - cloning the git repository already fails. I worked around that by cloning it from my host and bind mounting it into the container, but the build scripts also download tarballs from the internet which won't work either. That's when I discovered that the nameserver isn't reachable.

**Comment by m-kress** [comment]
Thanks for reporting this! You are absolutelly right: per default the IP address of the DNS is not useful.

When you use the VirtualBox SDK without the shared directory, the user is forced to get Internet connectivity within the SDK. In this case a correct DNS is essential.

When you use the SDK as a LXC container, the idea is exactly the way, you solved it: Install the container, clone the git repo with the build scripts using a shell of **outside** of your container into your HOME of your machine (not into the container) and finally mount the directory with the clone into the LXC container. That way the container doesn't need any Internet connectivity. Within the container you are supposed to **_run_** the build scripts, outside of the container you **_manage_** the build scripts (pull/push).

For the next version of the SDK we will modify the default DNS as you suggested.

Thanks again for reporting!

**Comment by NANASHI0X74** [comment]
a clarification - the build scripts won't run without internet either because they need to download multiple library tarballs as well.
A simple workaround is to just edit resolv.conf and change the nameserver from 192.168.200.2 to e.g. 1.1.1.1

**Comment by NANASHI0X74** [comment]
#22 I just realized I could create a PR about this and have some contribution in my profile :p feel free to use that, or choose a different nameserver. Or maybe the content of files is changed from outside of rootfs_skeleton, I'm not familiar with this project.

**Comment by m-kress** [comment]
Can we close this issue?

**Comment by NANASHI0X74** [comment]
Have you fixed the nameserver in the SDK container? ^^
But maybe we can close this regardless because I guess it really concerns a different project/codebase

**Comment by m-kress** [comment]
No, didn't "fix" it, as I dislike to put a currently publicly available IP address of a private company there. And I shot my foot already once, when I used a "free" and "open" accessible IP address in a product, which turned out to be offline after a few years.
In case you bridge IP net1 to the container, the default DNS works fine.

It might be a better idea to make it possible to configure the DNS for the container in the routers firmware, as it is already possible for the gateway.
