### ISSUE TITLE
create_container_default.sh failed to build (due to conflicting install location for several packages)

### ISSUE THREAD

**Issue by krishnan793** [insys-icom/M3_Container#29]
Followed installation steps as mentioned here using docker image.
https://hub.docker.com/r/insysicom/m3sdk_v5

`./scripts/create_container_default.sh`

```
Install: cannot create directory '/workspace/M3_Container/working/1z4-1.9.4/install': Not a directory install: cannot create directory '/workspace/M3_Container/working/1z4-1.9.4/install': Not a directory

make[1]: * [Makefile:182: install] Error 1 make[1]: Leaving directory '/workspace/M3_Container/working/1z4-1.9.4/lib


```
failed due to several individual build failure. While going through the logs, it seems to be due to the PKG_INSTALL_DIR path. The source already contains an INSTALL file and the script tried to create install directory. Since linux do not allow having a directory and file sharing same this is failing. Following build scripts failed due to this

1. pcre2-10.42.sh
2. metalog-20220214.sh
3. lz4-1.9.4.sh

There may be other scripts with same issue.

Fix suggestion:

change `PKG_INSTALL_DIR="${PKG_BUILD_DIR}/install"` to `PKG_INSTALL_DIR="${PKG_BUILD_DIR}/installd"`

**Comment by ctomahogh** [comment]
I heard the very same issue just last week.

The actual cause for this was, that the docker image was run on a Windows host machine in WSL2 and the case sensitivity was not active on the mounted partition.
This lead to the error, that the existing text file `INSTALL` blocked the WSL from creating the directory `install`, as on windows, these two files/directories are treated as being identical, where a Linux system treats these files as being separate files/directories.

As soon as the case sensitivity was activated for the mounted partition, all build scripts worked without errors.

So in case you are using WSL2, please make sure, that the case sensitivity is correctly enabled.
In general such an issue could arise in multiple ways during compiling, installation, ...
So I think, enabling case sensitivity in general for a build system designed for Linux targets is the better solution to not run in the same error "just a few steps further in the scripts"

**Comment by krishnan793** [comment]
@ctomahogh You are right. I am also running docker on windows WSL 2 with Ubuntu. Since usually the M3_Container is mounted as mentioned in the documentation (https://hub.docker.com/r/insysicom/m3sdk_v5) do you think it's better to change the install location (to support with docker running on windows as well)?

Or is there any way to mount with case sensitivity?

**Comment by ctomahogh** [comment]
No, a linux filesystem does not support having a file `abc` and a directory `abc`

But it does support having a file `ABC` and a directory `abc`

That is, whats happening at yours: There is already a textfile `INSTALL` (containing installation instructions) and a directory `install` should be created. Linux supports this.

```$ touch INSTALL
$ ls
INSTALL
$ mkdir install
$ ls -la
total 20
drwxr-xr-x  3 hawk hawk  4096 Apr  3 15:46 .
drwxr-xr-x 47 hawk hawk 12288 Apr  3 15:46 ..
drwxr-xr-x  2 hawk hawk  4096 Apr  3 15:46 install
-rw-r--r--  1 hawk hawk     0 Apr  3 15:46 INSTALL
```

But a windows machine does not support, having a file `INSTALL` and another file or directory `install`.
Therefor WSL does not allow this, if case sensitivity is not enabled.

**Comment by m-kress** [comment]
@krishnan793: Please also note, that no Windows file system supports symbolic (soft or hard) links. You will most likely run into trouble anyways just only for that.

**Comment by ctomahogh** [comment]
One approach, which might do the trick:

1. Open a terminal in wsl and create or open the file `/etc/wsl.conf`

`sudo nano /etc/wsl.conf`

2. Add the following lines at the end of the file and save it

```
[automount]
options = "case=strict"
```
3. Restart the WSL-Service to make the changes take effect
   `wsl --shutdown`

4. Restart the Linux-Docker-Container and check, that the file system is case-sensitive (see above commands)

All this is not verify by myself, so use at your own risk.

**Comment by krishnan793** [comment]
@ctomahogh Thanks. I will try this out.

**Comment by krishnan793** [comment]
`wsl.conf` entry created some warnings while mounting widows dirs... I have moved to a Linux VM and there is no issues.
