### ISSUE TITLE
Can't build default container

### ISSUE THREAD

**Issue by lipodat** [insys-icom/M3_Container#30]
I tried to do as the manual say, and here's what I got:

```
PS C:\> docker pull insysicom/m3sdk_v5
Using default tag: latest
latest: Pulling from insysicom/m3sdk_v5
fdc2327896ee: Pull complete
Digest: sha256:170ac7958995539501a094c06522b159140aef78bb16bbdec00e40ac83a0acc3
Status: Downloaded newer image for insysicom/m3sdk_v5:latest
docker.io/insysicom/m3sdk_v5:latest

What's Next?
  1. Sign in to your Docker account → docker login
  2. View a summary of image vulnerabilities and recommendations → docker scout quickview insysicom/m3sdk_v5
PS C:\> docker run --rm -it -v C:\M3_Container:/workspace insysicom/m3sdk_v5 /bin/bash --login
245baec63a06 / # cd workspace
245baec63a06 /workspace # git clone https://github.com/insys-icom/M3_Container.git
Cloning into 'M3_Container'...
remote: Enumerating objects: 6431, done.
remote: Counting objects: 100% (1191/1191), done.
remote: Compressing objects: 100% (400/400), done.
remote: Total 6431 (delta 825), reused 1118 (delta 760), pack-reused 5240
Receiving objects: 100% (6431/6431), 4.47 MiB | 8.01 MiB/s, done.
Resolving deltas: 100% (4440/4440), done.
Updating files: 100% (287/287), done.
245baec63a06 /workspace # cd M3_Container
245baec63a06 /workspace/M3_Container # ./scripts/create_container_default.sh

It is necessary to build these Open Source projects in this order:
- Linux-PAM-1.5.3.sh
- zlib-1.3.sh
- lz4-1.9.4.sh
- tzdb-2023d.sh
- pcre2-10.42.sh
- openssl-3.2.0.sh
- mcip.sh
- busybox-1.36.1.sh
- mcip-tool-v4.sh
- dropbear-2022.83.sh
- metalog-20230719.sh
- dnsmasq-2.89.sh

These packages only have to be compiled once. After that you can choose to only pack the container. Choose:
    b --- build all sources and pack the container
    p --- pack the container without building the sources
    c --- cancel, do nothing

b
Building everything

Downloading packages:
--------------------------------------------
    Downloading Linux-PAM-1.5.3.sh
    Downloading zlib-1.3.sh
    Downloading lz4-1.9.4.sh
    Downloading tzdb-2023d.sh
    Downloading pcre2-10.42.sh
    Downloading openssl-3.2.0.sh
    Downloading mcip.sh
    Downloading busybox-1.36.1.sh
    Downloading mcip-tool-v4.sh
    Downloading dropbear-2022.83.sh
    Downloading metalog-20230719.sh
    Downloading dnsmasq-2.89.sh

Uninstalling packages:
--------------------------------------------
    Uninstall Linux-PAM-1.5.3.sh
    Uninstall zlib-1.3.sh
    Uninstall lz4-1.9.4.sh
    Uninstall tzdb-2023d.sh
    Uninstall pcre2-10.42.sh
    Uninstall openssl-3.2.0.sh
    Uninstall mcip.sh
    Uninstall busybox-1.36.1.sh
    Uninstall mcip-tool-v4.sh
    Uninstall dropbear-2022.83.sh
    Uninstall metalog-20230719.sh
    Uninstall dnsmasq-2.89.sh

Compiling in parallel:
--------------------------------------------
    Compile Linux-PAM-1.5.3.sh
    Compile zlib-1.3.sh
    Compile lz4-1.9.4.sh
    Compile tzdb-2023d.sh
    Compile pcre2-10.42.sh
    Compile openssl-3.2.0.sh
    Compile mcip.sh
    ----------------------------------------
    Compile busybox-1.36.1.sh
    Compile mcip-tool-v4.sh
    Compile dropbear-2022.83.sh
    Compile metalog-20230719.sh
    Compile dnsmasq-2.89.sh
    ----------------------------------------
    ----------------------------------------

Packaging the container "container_default":
--------------------------------------------
  -> Creating archive /workspace/M3_Container/working/update/rootfs.tar containing the root file system
cp: cannot stat '/workspace/M3_Container/rootfs_staging/bin/busybox': No such file or directory
failed to copy /bin/busybox
```

**Comment by m-kress** [comment]
Hi!

you are building with Docker on Windows! I just quickly looked at your ticket, so a quick guess: Could it be a similar problem like the already closed ticket:
https://github.com/insys-icom/M3_Container/issues/29

If not please have a look at the file working/busybox-....log
Eventually the problem is the lacking softlink capability of windows?

**Comment by m-kress** [comment]
Most likely you will get into trouble because all Windows file systems lack proper support for symlinks. Especially busybox uses symlinks for its applets.

Eventually you can avoid file system trouble by not mounting anything or only subdirectories of M3_Container into the docker SDK, e.g. M3_Container/images, where all the built containers get stored. You would have to extract the M3_Container tar ball directly in the docker container.

Or you avoid using Windows completely ;-)

**Comment by m-kress** [comment]
By the way: there is a new SDK available as LXC container. You can create your own docker SDK container from that with only very few commands: https://github.com/insys-icom/M3_Container/blob/master/doc/Install_SDK_as_Docker_container.md
Alternatively you use the SDK on a Linux host directly as LXC container, which in my eyes is the much more comfortable than using docker.

**Comment by lipodat** [comment]
Maybe I should have explained my problem differently. I need to build a container for my .Net application. And this application is updated from time to time, so I would like to have some way to do it quickly and easily. Obviously, the development is done on Windows, so installing additional Linux just to build containers seems a bit cumbersome. Do you have any advice on how to make it easier?

**Comment by m-kress** [comment]
In your case my recommendation is:
- Start the SDK (as docker or LXC container)
- eventually set /etc/resolv.conf in the SDK, so you can get internet access from within the SDK
- clone the M3_Container repository into the SDK
- stop the SDK container and start it again with mounting single directories, that make file exchange with your host easier. Most liklely that would be
    - M3_Container/images  (this is, where the completelly packed containers end up)
    - M3_Container/closed_source (where you most probably will have you C# project in)

That way you create a container from scratch by building all the necessary OpenSource project (like busybox) on a Linux host. And you can compile your C# programs on Windows. the artefacts of your C# build will end up in M3_Container/closed_sources..... and you can integrate them into the final container by modifying the list file M3_Container/scripts/rootfs_default.txt.

There is a small Howto doc, which describes copiling C# projects without having the need for a runtime env in the container: 
https://github.com/insys-icom/M3_Container/blob/master/doc/HowTo_C%23.md

As a simple alternative you skip using the SDK and rely on the downloaded default container here: 
https://m3-container.net/M3_Container/images/container_default.tar
You would compile your application and scp it into the running container on the router. When everything works as you wish, you can download the container from there and use it on other devices.

**Comment by m-kress** [comment]
The thumbs up icons seems to indicate, that the issue has been solved. Please feel free to reopen this issue if that is not the case.
